
package com.mycompany.pryarchivos;

/**
 *
 * @author el profe ariel
 */
public class FrmProductos extends javax.swing.JFrame {

    private ModeloProductos modelo;
    
    public FrmProductos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        label1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        Apellido = new javax.swing.JTextField();
        Cedula = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(tblProductos);
        label1.setText("Nombre");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, 20));

        getContentPane().add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 150, 30));

        label2.setText("Apellido");
        getContentPane().add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 150, 20));

        getContentPane().add(Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 150, 30));

        label3.setText("Cedula");
        getContentPane().add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 150, 20));

        getContentPane().add(Cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 150, 30));

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 510, 213));

        modelo=new ModeloProductos();
        tblProductos.setModel(modelo);

        btn1.setFont(new java.awt.Font("Tahoma", 1, 24)); 
        btn1.setText("Agregar");
        btn1.addMouseListener(new java.awt.event.MouseAdapter() {
        
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn1MouseClicked(evt);
            }
        });
        getContentPane().add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 150, 50));
        btn2.setFont(new java.awt.Font("Tahoma", 1, 24));
        btn2.setText("Eliminar");
        btn2.addMouseListener(new java.awt.event.MouseAdapter() {
        
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn2MouseClicked(evt);
            }
        });
        getContentPane().add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 150, 50));
        btn3.setFont(new java.awt.Font("Tahoma", 1, 24)); 
        btn3.setText("Guardar");
        btn3.addMouseListener(new java.awt.event.MouseAdapter() {
        
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn3MouseClicked(evt);
            }
        });
        getContentPane().add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 150, 50));

        pack();
    }

    private void btn1MouseClicked(java.awt.event.MouseEvent evt) {
        
      System.out.println(tblProductos);
      String nombre=this.Nombre.getText();
      String apellido=this.Apellido.getText();
      Integer cedula=Integer.parseInt(Cedula.getText());
      Producto p =new Producto(nombre, apellido, cedula);
      modelo.agregarProducto(p);
      
    }
    private void btn2MouseClicked(java.awt.event.MouseEvent evt) {
        int fila=this.tblProductos.getSelectedRow();
        if(fila>=0){
            modelo.eliminarProducto(fila);
        }
    }
    private void btn3MouseClicked(java.awt.event.MouseEvent evt) {

        modelo.guardarProducto();
    }
    
     
    public static void main(String args[]) {
       
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmProductos().setVisible(true);
            }
        });
    }

    
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField Apellido;
    private javax.swing.JTextField Cedula;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProductos;
   
}
